#include <stdint.h>
#include <cpu/cpuid.hpp>

extern "C" __attribute__((naked)) void switchContext(void* oldContext, void* newContext) {
    asm volatile (
        ".intel_syntax noprefix\n"
        "push rdx\n"
        "cmp rcx, 0\n"
        "je .load_new\n"
        "mov [rcx + 0],  rax\n"
        "mov [rcx + 8],  rbx\n"
        "mov [rcx + 16], rcx\n"
        "mov [rcx + 24], rdx\n"
        "mov [rcx + 32], rsi\n"
        "mov [rcx + 40], rdi\n"
        "mov [rcx + 48], rbp\n"
        "lea rax, [rsp + 16]\n"
        "mov [rcx + 56], rax\n"
        "mov [rcx + 64], r8\n"
        "mov [rcx + 72], r9\n"
        "mov [rcx + 80], r10\n"
        "mov [rcx + 88], r11\n"
        "mov [rcx + 96], r12\n"
        "mov [rcx + 104], r13\n"
        "mov [rcx + 112], r14\n"
        "mov [rcx + 120], r15\n"
        "mov rax, [rsp + 8]\n"
        "mov [rcx + 128], rax\n"
        "pushfq\n"
        "pop rax\n"
        "mov [rcx + 136], rax\n"
        ".load_new:\n"
        "pop rsi\n"
        "mov r12, [rsi + 144]\n"
        "mov r13, [rsi + 136]\n"
        "mov r14, [rsi + 128]\n"
        "mov r15, [rsi + 56]\n"
        "mov cr3, r12\n"
        "mov rax, r13\n"
        "and rax, -513\n" // ~0x200
        "push rax\n"
        "popfq\n"
        "mov rsp, r15\n"
        "push r14\n"
        "mov rax, [rsi + 0]\n"
        "mov rbx, [rsi + 8]\n"
        "mov rcx, [rsi + 16]\n"
        "mov rdx, [rsi + 24]\n"
        "mov rdi, [rsi + 40]\n"
        "mov rbp, [rsi + 48]\n"
        "mov r8,  [rsi + 64]\n"
        "mov r9,  [rsi + 72]\n"
        "mov r10, [rsi + 80]\n"
        "mov r11, [rsi + 88]\n"
        "mov r12, [rsi + 96]\n"
        "mov r13, [rsi + 104]\n"
        "mov r14, [rsi + 112]\n"
        "mov r15, [rsi + 120]\n"
        "mov rsi, [rsi + 32]\n"
        "ret\n"
        ".att_syntax prefix\n"
    );
}

extern "C" __attribute__((naked)) void processTrampoline() {
    asm volatile (
        ".intel_syntax noprefix\n"
        "cli\n"
        "mov rax, [rsp + 0]\n"
        "mov rbx, [rsp + 8]\n"
        "add rsp, 16\n"
        "push 0x1B\n"
        "push rbx\n"
        "pushfq\n"
        "pop rcx\n"
        "or rcx, 0x200\n"
        "push rcx\n"
        "push 0x23\n"
        "push rax\n"
        "xor rax, rax\n"
        "xor rbx, rbx\n"
        "xor rcx, rcx\n"
        "xor rdx, rdx\n"
        "xor rsi, rsi\n"
        "xor rdi, rdi\n"
        "xor rbp, rbp\n"
        "xor r8, r8\n"
        "xor r9, r9\n"
        "xor r10, r10\n"
        "xor r11, r11\n"
        "xor r12, r12\n"
        "xor r13, r13\n"
        "xor r14, r14\n"
        "xor r15, r15\n"
        "mov ecx, 0xC0000102\n"
        "rdmsr\n"
        "test eax, eax\n"
        "jne 1f\n"
        "test edx, edx\n"
        "jne 1f\n"
        "swapgs\n"
        "1:\n"
        "iretq\n"
        ".att_syntax prefix\n"
    );
}

extern "C" __attribute__((naked)) void threadTrampoline() {
    asm volatile (
        ".intel_syntax noprefix\n"
        "cli\n"
        "mov rax, [rsp + 0]\n"
        "mov rbx, [rsp + 8]\n"
        "mov rdi, [rsp + 16]\n"
        "add rsp, 24\n"
        "push 0x1B\n"
        "push rbx\n"
        "pushfq\n"
        "pop rcx\n"
        "or rcx, 0x200\n"
        "push rcx\n"
        "push 0x23\n"
        "push rax\n"
        "xor rax, rax\n"
        "xor rbx, rbx\n"
        "xor rdx, rdx\n"
        "xor rsi, rsi\n"
        "xor rbp, rbp\n"
        "xor r8, r8\n"
        "xor r9, r9\n"
        "xor r10, r10\n"
        "xor r11, r11\n"
        "xor r12, r12\n"
        "xor r13, r13\n"
        "xor r14, r14\n"
        "xor r15, r15\n"
        "mov ecx, 0xC0000102\n"
        "rdmsr\n"
        "test eax, eax\n"
        "jne 1f\n"
        "test edx, edx\n"
        "jne 1f\n"
        "swapgs\n"
        "1:\n"
        "mov rcx, rdi\n"
        "iretq\n"
        ".att_syntax prefix\n"
    );
}
